### ISSUE TITLE
Any Ubuntu / Debian packages

### ISSUE THREAD

**Issue by bklooste** [fullstorydev/grpcurl#253]
Spend a bit of time searching through your packges as instructed in the readme but nothing for Ubuntu / Debian...

**Comment by fireXtract** [comment]
Use the binary from the releases page https://github.com/fullstorydev/grpcurl/releases

**Comment by hwittenborn** [comment]
If there's still interest in this, [makedeb](https://makedeb.org) (a personal project) should work well, and would likely only require maintaining a single Bash file in this repository.

**Comment by acabarbaye** [comment]
Since goreleaser is used, it is just a matter of adding the following section to the configuration file
```
nfpms:
  - formats:
      - apk
      - deb
      - rpm
    license: Apache-2.0
    maintainer: <>
```
