### ISSUE TITLE
How to access Kubernetes GRPC Ingress calls with prefix?

### ISSUE THREAD

**Issue by GautamSinghania** [fullstorydev/grpcurl#347]
We are using GRPC Ingress with Kubernetes and multiple paths. Here is the yaml:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grpc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: xxx.xxx.internal
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: service-1
            port:
              number: 5001
      - path: /prefix-2/(.*)
        pathType: Prefix
        backend:
          service:
            name: service-2
            port:
              number: 5001
  tls:
  - secretName: grpc-tls
    hosts:
    - xxx.xxx.internal
```

We have the proto file for this, and tried hitting the services using
```sh
grpcurl -d '<<DATA>>' -proto <<PROTO_FILE>> -insecure xxx.xxx.internal:443 tensorflow.serving.PredictionService.Predict
```

We are able to hit `service-1`, which does not have any prefix. However, we are not able to hit `service-2`. We tried using `xxx.xxx.internal:443/test` and `/test/tensorflow.serving.PredictionService.Predict`, but none of them work.

We know that there is a Go script that can access this. Can you do a similar thing for grpcurl?

**Comment by jhump** [comment]
@GautamSinghania, does this mean the URLs for service-2 require a path prefix of `/prefix-2/`? That is generally not valid in gRPC. 

The [protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) for gRPC explicitly states that the path should be like so:
> "/" Service-Name "/" {method name}

For this reason, none of the official gRPC clients will be able to access the service you are configuring since base paths are not supported. What kind of client are you using where you can make use of endpoints like that?

**Comment by GautamSinghania** [comment]
We were using Go. I have asked my colleague working on this to create a script for testing purposes, will share that here once complete.

**Comment by GautamSinghania** [comment]
As a standards question, what would be your suggestion to using multiple services under the same Ingress endpoint?

**Comment by jhump** [comment]
> what would be your suggestion to using multiple services under the same Ingress endpoint?

Two ways
1. The simplest is to dispatch to one or the other based on the fully-qualified service name. So one service's ingress could enumerate all of the RPC services it exposes. A different service has an ingress that lists different service names. Obviously, having two services implement the same RPC service name will not work. (Though this can be problematic for other reasons, and is usually easily avoided.)
2. Use vhosts/sub-domains. This allows for multiple services exposing the same service name. This is how Google Cloud works, where multiple sub-domains of googleapis.com (firebase, datastore, bigtable, appengine, etc) all implement the [long-running operations service](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto).

**Comment by thunder7553** [comment]
> @GautamSinghania, does this mean the URLs for service-2 require a path prefix of `/prefix-2/`? That is generally not valid in gRPC.
> 
> The [protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) for gRPC explicitly states that the path should be like so:
> 
> > "/" Service-Name "/" {method name}
> 
> For this reason, none of the official gRPC clients will be able to access the service you are configuring since base paths are not supported. What kind of client are you using where you can make use of endpoints like that?

I face the same problem - I do have a .NET 6 application (server and client), and the customer demands to have it in `https://somehostname/<app>/` - <app> would be the prefix. From what I understand [here](https://github.com/grpc/grpc/blob/master/doc/grpc_xds_features.md), it would be the "Request matching based on Prefix" [A28](https://github.com/grpc/proposal/blob/master/A28-xds-traffic-splitting-and-routing.md)

I did not follow gRPC development until now, so I do not know how this RFCs are applied. But from what I understand, it should be supported in the official clients.

**Comment by thunder7553** [comment]
FWIW, how to host a GRPC service in a directory in .NET 6 is documented on [learn.microsoft.com](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#calling-grpc-services-hosted-in-a-sub-directory)

**Comment by jhump** [comment]
> would be the prefix. From what I understand [here](https://github.com/grpc/grpc/blob/master/doc/grpc_xds_features.md), it would be the "Request matching based on Prefix" [A28](https://github.com/grpc/proposal/blob/master/A28-xds-traffic-splitting-and-routing.md)

@thunder7553, that proposal is for configuring XDS clients to support path matching for routing. But that does not mention anything about _custom_ path prefixes. The gRPC Go client still has no option for specifying a base URI path, and the HTTP/2 wire spec still has no mention of support for a custom path prefix. FWIW, they are not server-side: XDS is a protocol for _client_-side load balancing, so it configures how clients should route requests to different discovered backends.

> FWIW, how to access a GRPC service hosted in a directory in .NET 6 is documented on [learn.microsoft.com](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#calling-grpc-services-hosted-in-a-sub-directory)

Note the big warning at the top of that page.

**Comment by thunder7553** [comment]
Thanks for the info, you are right indeed. I have to dig into that.

**Comment by renevall** [comment]
@thunder7553 This is what worked for me:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "places"
  labels:
    app: "places"
    monitor: "true"
spec:
  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 50051
  selector:
    app: "places"

--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: "tracker"
spec:
  ingressClassName: nginx
  rules:
  - host: "dev.something.com"
    http:
      paths:
      - path: /org.places.v1.PlacesService # use package.ServiceName
        pathType: Prefix
        backend:
          service:
            name: "dev"
            port:
              number: 80
  tls:
    - hosts:
        - "dev.something.com"
      secretName: "dev.something.com-tls"

```

Then this will work:

```sh
grpcurl -import-path path/to/proto -proto service.proto -v -d '{"id":"018bd0c9-1ef2-788b-945f-a437e28b2a1c"}' \
    dev.something.com:443 org.places.v1.PlacesService/GetPlace
```

I have not managed to make the reflection work. This is because nginx gets `/grpc.reflection.v1.ServerReflection/ServerReflectionInfo` as the path. If we were able to get `/org.places.v1.PlacesService/grpc.reflection.v1.ServerReflection/ServerReflectionInfo` it would work since then nginx would know what path to take. 

CC @jhump
